####Install the most needed packages to run####
library(plotly)
library(shinyBS)
library(shinyalert)
library(shinybusy)
library(shinycustomloader)
library(shinyWidgets)
library(shinydashboard)
library(shinydashboardPlus)
library(shinyjs)
library(shiny)
library(rstudioapi)
library(tryCatchLog)
library(esquisse)
library(scales)
library(gtools)
library(shinyFiles)
library(purrr)
library(vroom)
library(tools)
library(DataEditR)
library(ggplot2)
library(patchwork)
library(plotly)
library(dplyr)
library(ggprism)
library(ggthemes)
library(smoother)
library(stringr)
library(matrixStats)
library(fontawesome)
library(tidyr)
library(latex2exp)
library(ggpubr)
library(magrittr)
library(rvg)
library(officer)

source("utils.R")
isDataImported <- FALSE
isCalculated <- FALSE
isDataSaved <- FALSE
dataList <- list()

colorPalette <- c("#000000", "#0072B2", "#009E73",
                  "#D55E00", "#56B4E9", "#F0E442",
                  "#CC79A7", "#999999", "#E69F00")
colorChoices <-  list(Median = colorPalette, Statistic = colorPalette)
colorSelected <-  list(Median = colorPalette, Statistic = colorPalette)
selectedColors <- list(Median = c(), Statistic = c())
seriesList <- list(all = c(), Median = c(), Statistic = c())
